# Generated by Django 3.2.9 on 2021-12-02 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.IntegerField(choices=[(0, 'Выберите р-н БЦ'), (1, 'Аламалинский р-н'), (2, 'Бостандыкский р-н')])),
                ('address', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCenterOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=240)),
                ('room', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('business_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='business.businesscenter')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('bin_iin', models.CharField(max_length=30)),
                ('iik', models.CharField(max_length=100)),
                ('bik', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Выберите форму предпринимательства Вашей организации'), (1, 'ТОО'), (2, 'ИП'), (3, 'АО')])),
                ('is_init', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Еще не соствавлен'), (1, 'Одобренно'), (2, 'Отклоненно'), (3, 'В ожидании')], default=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
            ],
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('distributor', models.CharField(max_length=60)),
                ('type', models.IntegerField(choices=[(1, 'Стол'), (2, 'Компьютер')])),
                ('for_position', models.IntegerField(choices=[(0, 'Выберите должность'), (1, 'Back-end программист'), (2, 'Front-end программист'), (3, 'Web - дизайнер'), (4, 'Для всех')])),
            ],
        ),
        migrations.CreateModel(
            name='ThingToCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.things')),
            ],
        ),
        migrations.CreateModel(
            name='ThingsToOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things_to_order', to='business.order')),
                ('things', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.things')),
            ],
        ),
        migrations.CreateModel(
            name='OfficesToOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businesscenteroffice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_to_order', to='business.order')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(0, 'Выберите должность'), (1, 'Back-end программист'), (2, 'Front-end программист'), (3, 'Web - дизайнер')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCenterOfficeToCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
                ('offices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businesscenteroffice')),
            ],
        ),
    ]
